#!/usr/bin/env python3
"""Apply this project's translation memory on top of ZedG translations."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any


INLINE_CODE_RE = re.compile(r"(?<!`)`([^`\n]+)`(?!`)")
FENCE_LANG_RE = re.compile(r"```([^\s`\\{]+)")
TRANSLATED_FILENAME_REPLACEMENTS = {
    "设置.json": "settings.json",
    ".zed/设置.json": ".zed/settings.json",
    "键位映射.json": "keymap.json",
    "键位.json": "keymap.json",
    "任务.json": "tasks.json",
    "调试.json": "debug.json",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--strings",
        required=True,
        help="ZedG string.json extracted from the target Zed source.",
    )
    parser.add_argument(
        "--translation",
        required=True,
        help="ZedG translation JSON to overlay, for example i18n/vX/zh-CN.json.",
    )
    parser.add_argument(
        "--memory",
        default="translations/translation-memory.json",
        help="Translation memory generated by build_translation_memory.py.",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Output translation JSON after applying the overlay.",
    )
    parser.add_argument(
        "--report",
        help="Optional JSON report path.",
    )
    parser.add_argument(
        "--no-guardrails",
        action="store_true",
        help="Only apply memory overrides; do not repair protected code/file text.",
    )
    return parser.parse_args()


def load_json(path: Path, default: Any | None = None) -> Any:
    if not path.exists():
        if default is not None:
            return default
        raise SystemExit(f"file not found: {path}")
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def save_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(data, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def contains_cjk(text: str) -> bool:
    return any("\u4e00" <= char <= "\u9fff" for char in text)


def memory_exact(memory: dict[str, Any]) -> dict[str, str]:
    result: dict[str, str] = {}
    for record in memory.get("exact", []):
        source = (record.get("source") or "").strip()
        target = (record.get("target") or "").strip()
        if source and target and contains_cjk(target):
            result[source] = target
    return result


def code_like(text: str) -> bool:
    if not text or not any(char.isascii() and char.isalpha() for char in text):
        return False
    if re.fullmatch(r"\{[^}]*\}", text):
        return False
    if any(mark in text for mark in (".", "/", "\\", ":", "::", "-", "_")):
        return True
    words = text.split()
    return len(words) <= 5 and any(word.islower() for word in words)


def replace_nth_inline_code(text: str, index: int, new_code: str) -> str:
    count = -1

    def repl(match: re.Match[str]) -> str:
        nonlocal count
        count += 1
        if count == index:
            return f"`{new_code}`"
        return match.group(0)

    return INLINE_CODE_RE.sub(repl, text)


def restore_inline_code(original: str, translated: str) -> tuple[str, list[str]]:
    fixes: list[str] = []
    original_codes = INLINE_CODE_RE.findall(original)
    translated_codes = INLINE_CODE_RE.findall(translated)
    if not original_codes or len(original_codes) != len(translated_codes):
        return translated, fixes

    result = translated
    for index, original_code in enumerate(original_codes):
        current_codes = INLINE_CODE_RE.findall(result)
        if index >= len(current_codes):
            break
        translated_code = current_codes[index]
        if original_code == translated_code or not code_like(original_code):
            continue
        if contains_cjk(translated_code) or original_code not in result:
            result = replace_nth_inline_code(result, index, original_code)
            fixes.append(f"inline_code:{translated_code}->{original_code}")
    return result, fixes


def restore_fence_languages(original: str, translated: str) -> tuple[str, list[str]]:
    fixes: list[str] = []
    source_langs = FENCE_LANG_RE.findall(original)
    target_langs = FENCE_LANG_RE.findall(translated)
    if not source_langs or len(source_langs) != len(target_langs):
        return translated, fixes

    result = translated
    for source_lang, target_lang in zip(source_langs, target_langs):
        if source_lang == target_lang:
            continue
        if contains_cjk(target_lang):
            result = result.replace(f"```{target_lang}", f"```{source_lang}", 1)
            fixes.append(f"fence_lang:{target_lang}->{source_lang}")
    return result, fixes


def restore_filenames(original: str, translated: str) -> tuple[str, list[str]]:
    fixes: list[str] = []
    result = translated
    for bad, good in TRANSLATED_FILENAME_REPLACEMENTS.items():
        if bad in result and good in original:
            result = result.replace(bad, good)
            fixes.append(f"filename:{bad}->{good}")
    return result, fixes


def apply_guardrails(original: str, translated: str) -> tuple[str, list[str]]:
    result, fixes = restore_filenames(original, translated)
    result, inline_fixes = restore_inline_code(original, result)
    result, fence_fixes = restore_fence_languages(original, result)
    return result, fixes + inline_fixes + fence_fixes


def overlay_translations(
    strings: dict[str, dict[str, str]],
    translations: dict[str, dict[str, str]],
    exact: dict[str, str],
    use_guardrails: bool,
) -> tuple[dict[str, dict[str, str]], dict[str, Any]]:
    result: dict[str, dict[str, str]] = {
        file_path: dict(pairs) for file_path, pairs in translations.items()
    }
    stats = {
        "files_seen": len(strings),
        "strings_seen": 0,
        "memory_added": 0,
        "memory_updated": 0,
        "memory_same": 0,
        "guardrail_fixed": 0,
        "missing_after_overlay": 0,
    }
    report_items: list[dict[str, str]] = []

    for file_path, pairs in strings.items():
        out_pairs = result.setdefault(file_path, {})
        for source in pairs:
            stats["strings_seen"] += 1
            previous = out_pairs.get(source, "")
            if source in exact:
                target = exact[source]
                if previous == target:
                    stats["memory_same"] += 1
                elif previous:
                    stats["memory_updated"] += 1
                    report_items.append(
                        {
                            "kind": "memory_updated",
                            "file": file_path,
                            "source": source,
                            "before": previous,
                            "after": target,
                        }
                    )
                else:
                    stats["memory_added"] += 1
                out_pairs[source] = target
                continue

            if use_guardrails and previous:
                fixed, fixes = apply_guardrails(source, previous)
                if fixes and fixed != previous:
                    stats["guardrail_fixed"] += 1
                    out_pairs[source] = fixed
                    report_items.append(
                        {
                            "kind": "guardrail_fixed",
                            "file": file_path,
                            "source": source,
                            "before": previous,
                            "after": fixed,
                            "fixes": ", ".join(fixes),
                        }
                    )

            if not out_pairs.get(source):
                stats["missing_after_overlay"] += 1

    report = {"stats": stats, "items": report_items}
    return result, report


def main() -> int:
    args = parse_args()
    strings = load_json(Path(args.strings))
    translations = load_json(Path(args.translation), default={})
    memory = load_json(Path(args.memory))

    result, report = overlay_translations(
        strings=strings,
        translations=translations,
        exact=memory_exact(memory),
        use_guardrails=not args.no_guardrails,
    )
    save_json(Path(args.output), result)
    if args.report:
        save_json(Path(args.report), report)

    stats = report["stats"]
    print(
        "overlay complete: "
        f"files={stats['files_seen']} strings={stats['strings_seen']} "
        f"memory_added={stats['memory_added']} "
        f"memory_updated={stats['memory_updated']} "
        f"guardrail_fixed={stats['guardrail_fixed']} "
        f"missing={stats['missing_after_overlay']}"
    )
    print(f"output: {Path(args.output)}")
    if args.report:
        print(f"report: {Path(args.report)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
